Module 8: Typescript
ReCoded-Org/curriculum-backend-readings pull request #11
Opened 2021-10-05 23:48 UTC by louisrli

2022-01-04 11:14 UTC, halitbatur requested changes

2022-01-04 11:14 UTC, halitbatur commented on module8-typescript/r1.1-classes-and-interfaces/README.md
> +class RecodedStudent {
missing the `extends` keyword

2022-01-04 11:14 UTC, halitbatur commented on module8-typescript/r1.1-classes-and-interfaces/README.md
> +In the example above, we have two iterfaces: `Colorful` and `Circle`. If we want
interfaces*

2022-01-04 11:14 UTC, halitbatur commented on module8-typescript/r2-advanced-types/README.md
> +      return "white";
This line should be after line 46

2022-01-04 11:14 UTC, halitbatur commented on module8-typescript/r2-advanced-types/README.md
> +intersection type instead *combines* all of the given types.
no examples were mentioned for intersection types.

2022-06-25 17:29 UTC, wisammechano approved these changes
Made the necessary changes for version 1 of the module

2022-06-25 17:30 UTC, wisammechano commented
Moved to Canvas

2022-06-25 17:30 UTC, merged